---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wasm-files-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: ${VOLUME_SIZE}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/wasm-files"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-wasm-files
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${VOLUME_SIZE}
---
# Create a pod to copy manualy files to the PersistentVolume
apiVersion: v1
kind: Pod
metadata:
  name: wasm-files-store
spec:
  volumes:
    - name: wasm-files-storage
      persistentVolumeClaim:
        claimName: pv-claim-wasm-files
  containers:
    - name: wasm-files-container
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /wasm-files
          name: wasm-files-storage

