# k8s/manifests/wasm-files-volume.yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-wasm-registry-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: ${REGISTRY_SIZE}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/wasm-registry-files"
---
# A cluster running on Civo will have civo-volume as the default storage class. 
# This can be confirmed by viewing the storageclass resources on your cluster:
# kubectl get sc

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-wasm-registry-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${REGISTRY_SIZE}
---
# Create a pod to copy manualy files to the PersistentVolume
apiVersion: v1
kind: Pod
metadata:
  name: wasm-registry-store
spec:
  volumes:
    - name: wasm-registry-storage
      persistentVolumeClaim:
        claimName: task-pv-wasm-registry-claim
  containers:
    - name: wasm-registry-container
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: /wasm-registry-files
          name: wasm-registry-storage

